// This file is auto-generated by @hey-api/openapi-ts

export type CustomMessage = {
    readonly msg: string;
};

export type Login = {
    password: string;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    first_name?: string;
    last_name?: string;
    /**
     * Email address
     */
    email?: string;
    uuid?: string;
    phone_number: number;
};

export type CoreLoginDestroyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/core/login/';
};

export type CoreLoginDestroyResponses = {
    /**
     * Indicates that the operation is successfull.
     */
    200: CustomMessage;
};

export type CoreLoginDestroyResponse = CoreLoginDestroyResponses[keyof CoreLoginDestroyResponses];

export type CoreLoginRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/core/login/';
};

export type CoreLoginRetrieveResponses = {
    /**
     * Indicates that the operation is successfull.
     */
    200: Login;
};

export type CoreLoginRetrieveResponse = CoreLoginRetrieveResponses[keyof CoreLoginRetrieveResponses];

export type CoreLoginCreateData = {
    body?: never;
    headers: {
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/core/login/';
};

export type CoreLoginCreateResponses = {
    /**
     * Indicates that the operation is successfull.
     */
    201: CustomMessage;
};

export type CoreLoginCreateResponse = CoreLoginCreateResponses[keyof CoreLoginCreateResponses];

export type CoreQrAuthRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/core/qr-auth/';
};

export type CoreQrAuthRetrieveResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type CoreQrAuthCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/core/qr-auth/';
};

export type CoreQrAuthCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type CoreQrAuthUpdateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/core/qr-auth/';
};

export type CoreQrAuthUpdateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type ClientOptions = {
    baseURL: 'http://10.21.97.249:8001' | (string & {});
};