// This file is auto-generated by @hey-api/openapi-ts

export type CustomMessage = {
    readonly msg: string;
};

export type DeviceIdentification = {
    uuid: string;
    readonly path: string;
    verification_status?: boolean;
};

export type Login = {
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    first_name?: string;
    last_name?: string;
    /**
     * Email address
     */
    email?: string;
    uuid?: string;
    phone_number: number;
};

export type DeviceIdentificationWritable = {
    uuid: string;
    verification_status?: boolean;
};

export type CoreLoginDestroyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/core/login/';
};

export type CoreLoginDestroyResponses = {
    /**
     * Indicates that the operation is successfull.
     */
    200: CustomMessage;
};

export type CoreLoginDestroyResponse = CoreLoginDestroyResponses[keyof CoreLoginDestroyResponses];

export type CoreLoginRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/core/login/';
};

export type CoreLoginRetrieveResponses = {
    /**
     * Indicates that the operation is successfull.
     */
    200: Login;
};

export type CoreLoginRetrieveResponse = CoreLoginRetrieveResponses[keyof CoreLoginRetrieveResponses];

export type CoreLoginCreateData = {
    body?: never;
    headers: {
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/core/login/';
};

export type CoreLoginCreateResponses = {
    /**
     * Indicates that the operation is successfull.
     */
    201: CustomMessage;
};

export type CoreLoginCreateResponse = CoreLoginCreateResponses[keyof CoreLoginCreateResponses];

export type CoreQrAuthRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/core/qr-auth/';
};

export type CoreQrAuthRetrieveResponses = {
    /**
     * Indicates that the operation is successfull.
     */
    200: DeviceIdentification;
};

export type CoreQrAuthRetrieveResponse = CoreQrAuthRetrieveResponses[keyof CoreQrAuthRetrieveResponses];

export type CoreQrAuthCreateData = {
    body?: {
        /**
         * UUID Field
         */
        uuid?: string;
    };
    path?: never;
    query?: never;
    url: '/core/qr-auth/';
};

export type CoreQrAuthCreateResponses = {
    /**
     * Indicates that the operation is successfull.
     */
    201: CustomMessage;
};

export type CoreQrAuthCreateResponse = CoreQrAuthCreateResponses[keyof CoreQrAuthCreateResponses];

export type CoreQrAuthUpdateData = {
    body?: {
        /**
         * Token scanned after decoding QR code.
         */
        scanned_token: string;
    };
    path?: never;
    query?: never;
    url: '/core/qr-auth/';
};

export type CoreQrAuthUpdateResponses = {
    /**
     * Indicates that the operation is successfull.
     */
    200: CustomMessage;
};

export type CoreQrAuthUpdateResponse = CoreQrAuthUpdateResponses[keyof CoreQrAuthUpdateResponses];

export type ClientOptions = {
    baseURL: 'http://10.21.97.249:8001' | (string & {});
};